baseURL = '/'
languageCode = 'fr-fr'
title = 'Portfolio'
theme = 'iutdelens'
paginate = 5

[params]
    author = "JAKOBOWSKI Aymeric"
    authorImage = "/images/parametres/photoProfil.svg"

[[menu.main]]
    name = "Projets"
    url = "/projets"

[[menu.main]]
    name = "Catégories"
    url = "/categories"

[[menu.main]]
    name = "Compétences"
    url = "/competences"

[[menu.social]]
    name = "GitLab"
    url = "https://gitlab.univ-artois.fr/aymeric_jakobowski"
    pre = "<i class='fab fa-gitlab'></i>"

[[menu.social]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/aymeric-jakobowski"
    pre = "<i class='fab fa-linkedin'></i>"

[[menu.footer]]
    name = "Projets"
    url = "/projets"

[[menu.footer]]
    name = "Catégories"
    url = "/categories"

[[menu.footer]]
    name = "Compétences"
    url = "/competences"
