baseURL = '/'
languageCode = 'fr-fr'
title = 'Portfolio'
theme = 'iutdelens'
paginate = 4
defaultContentLanguage = 'fr'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "JAKOBOWSKI Aymeric"
    authorImage = "/images/parametres/photoProfil.svg"

[languages]
    [languages.fr]
        contentDir = "content/french"
        title = "Portfolio"
        languageName = "Français"
        flagImage = "/images/parametres/frenchFlag.png"
        weight = 1

        [languages.fr.menu]
[[languages.fr.menu.main]]
    name = "Projets"
    url = "/projets"
[[languages.fr.menu.main]]
    name = "Catégories"
    url = "/categories"
[[languages.fr.menu.main]]
    name = "Compétences"
    url = "/competences"
[[languages.fr.menu.main]]
    name = "Certifications"
    url = "/certifications"

[[languages.fr.menu.social]]
    name = "GitHub"
    url = "https://github.com/AymericJak"
    pre = "<i class='fab fa-github'></i>"
[[languages.fr.menu.social]]
    name = "Linkedin-fr"
    url = "https://www.linkedin.com/in/aymeric-jakobowski"
    pre = "<i class='fab fa-linkedin'></i>"

[[languages.fr.menu.footer]]
    name = "Projets"
    url = "/projets"
[[languages.fr.menu.footer]]
    name = "Catégories"
    url = "/categories"
[[languages.fr.menu.footer]]
    name = "Compétences"
    url = "/competences"
[[languages.fr.menu.footer]]
    name = "Certifications"
    url = "/certifications"
[[languages.fr.menu.footer]]
name = "Évènements"
url = "/evenements"
[[languages.fr.menu.footer]]
name = "Bénévolat"
url = "/benevolat"


    [languages.en]
        contentDir = "content/english"
        title = "Portfolio"
        languageName = "English"
        flagImage = "/images/parametres/englishFlag.png"
        weight = 2
        
        [languages.en.menu]
[[languages.en.menu.main]]
    name = "Projects"
    url = "/en/projets/"
[[languages.en.menu.main]]
    name = "Categories"
    url = "/en/categories"
[[languages.en.menu.main]]
    name = "Skills"
    url = "/en/skills-en"
[[languages.en.menu.main]]
    name = "Certifications"
    url = "/en/certifications-en"

[[languages.en.menu.social]]
    name = "GitHub"
    url = "https://github.com/AymericJak"
    pre = "<i class='fab fa-github'></i>"
[[languages.en.menu.social]]
    name = "Linkedin-en"
    url = "https://www.linkedin.com/in/aymeric-jakobowski/en"
    pre = "<i class='fab fa-linkedin'></i>"

[[languages.en.menu.footer]]
    name = "Projects"
    url = "/en/projets"
[[languages.en.menu.footer]]
    name = "Categories"
    url = "/en/categories"
[[languages.en.menu.footer]]
    name = "Skills"
    url = "/en/skills-en"
[[languages.en.menu.footer]]
    name = "Certifications"
    url = "/en/certifications-en"
[[languages.en.menu.footer]]
    name = "Events"
    url = "/en/events"
[[languages.en.menu.footer]]
    name = "Volunteering"
    url = "/en/benevolat"
